"""create subscribe model

Revision ID: 83018bd89209
Revises: 7a1df4e8cd27
Create Date: 2021-05-02 16:19:35.568594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83018bd89209'
down_revision = '7a1df4e8cd27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
