"""update posts model

Revision ID: faf9f898afe1
Revises: ae120a8c7686
Create Date: 2021-04-30 23:13:14.148493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faf9f898afe1'
down_revision = 'ae120a8c7686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('post_content', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('short_description', sa.String(), nullable=True))
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'date_posted')
    op.drop_column('posts', 'user_id')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('posts', 'short_description')
    op.drop_column('posts', 'posted')
    op.drop_column('posts', 'post_content')
    op.drop_column('posts', 'author_id')
    # ### end Alembic commands ###
